/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.17
 * Generated at: 2022-05-23 05:45:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<footer class=\"text-center text-white\"\r\n");
      out.write("\tstyle=\"background-image: radial-gradient(circle at 119.64% 37.72%, #18344a 0, #010912 50%, #000000 100%);\">\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<div class=\"container p-4\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"row fs-6\">\r\n");
      out.write("\t\t\t<div class=\"col-lg-3 mb-6 mb-lg-0\">\r\n");
      out.write("\t\t\t\t<h5 class=\"text-uppercase\">UBICACIÓN</h5>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\tAv. Abancay 5, <br> Cercado de Lima 15001\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-lg-6 mb-12 mb-lg-0\">\r\n");
      out.write("\t\t\t\t<!-- Section: Social media -->\r\n");
      out.write("\t\t\t\t<section class=\"mb-4\">\r\n");
      out.write("\t\t\t\t\t<h4>Ministerio Público - Fiscalía de la Nación 2022</h4>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<a class=\"btn btn-outline-light btn-social mx-1\"\r\n");
      out.write("\t\t\t\t\t\thref=\"https://es-la.facebook.com/\"><i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fab fa-fw fa-facebook-f\"></i></a> <a\r\n");
      out.write("\t\t\t\t\t\tclass=\"btn btn-outline-light btn-social mx-1\"\r\n");
      out.write("\t\t\t\t\t\thref=\"https://twitter.com/\"><i class=\"fab fa-fw fa-twitter\"></i></a>\r\n");
      out.write("\t\t\t\t\t<a class=\"btn btn-outline-light btn-social mx-1\"\r\n");
      out.write("\t\t\t\t\t\thref=\"https://www.youtube.com/\"><i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fab fa-fw fa-youtube\"></i></a>\r\n");
      out.write("\t\t\t\t</section>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--Grid column-->\r\n");
      out.write("\t\t\t<div class=\"col-lg-3 mb-6 mb-lg-0\">\r\n");
      out.write("\t\t\t\t<h5 class=\"text-uppercase\">CONTACTO</h5>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\tCentral Telefónica: <br> 625-5555<br> Línea Gratuita:<br>\r\n");
      out.write("\t\t\t\t\t0-800-00-205\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"text-center p-3\"\r\n");
      out.write("\t\tstyle=\"background-color: rgba(0, 0, 0, 0.2);\">© Derechos\r\n");
      out.write("\t\tReservados</div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"\r\n");
      out.write("\tintegrity=\"sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("\tintegrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- JS para validación-->\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdn.bootcdn.net/ajax/libs/bootstrap-validator/0.4.0/js/bootstrapValidator.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tvar popoverTriggerList = [].slice.call(document\r\n");
      out.write("\t\t\t.querySelectorAll('[data-bs-toggle=\"popover\"]'))\r\n");
      out.write("\tvar popoverList = popoverTriggerList.map(function(popoverTriggerEl) {\r\n");
      out.write("\t\treturn new bootstrap.Popover(popoverTriggerEl)\r\n");
      out.write("\t})\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
